name: typephp-ext-aes

sources:
  - src/EncryptionUtil.php

ignore:

output: build/typephp-ext-aes
mode: ext
extension-dependencies:
  - openssl
php-version: "8.5"
cxx-std: c++17
optimize: 2
job: 1
debug: true
